# Generated by Django 2.1.5 on 2019-01-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=16)),
                ('number', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('body', models.CharField(default='', max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='courtorder',
            index=models.Index(fields=['date'], name='core_courto_date_f1c9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='courtorder',
            index=models.Index(fields=['body'], name='core_courto_body_6656e9_idx'),
        ),
        migrations.AddIndex(
            model_name='courtorder',
            index=models.Index(fields=['name'], name='core_courto_name_a429c3_idx'),
        ),
        migrations.AddIndex(
            model_name='courtorder',
            index=models.Index(fields=['source', 'number'], name='core_courto_source_6134bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courtorder',
            unique_together={('source', 'number')},
        ),
    ]
