# Generated by Django 2.1.5 on 2019-01-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sort_court_orders_by_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtorder',
            name='body',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='courtorder',
            name='number',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='courtorder',
            name='text',
            field=models.TextField(),
        ),
    ]
