# Generated by Django 2.1.5 on 2019-01-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_allow_court_order_number_to_store_longer_texts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courtorder',
            unique_together={('source', 'number', 'name', 'date', 'body')},
        ),
    ]
