# Generated by Django 2.1.5 on 2019-02-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_extend_unique_together_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtOrderTJSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('decision', models.TextField()),
                ('decision_date', models.DateField()),
                ('status', models.TextField(default='')),
                ('source_numbers', models.TextField(default='')),
                ('reporter', models.TextField(default='')),
                ('category', models.TextField(default='')),
                ('petitioner', models.TextField(default='')),
                ('requested', models.TextField(default='')),
            ],
            options={
                'ordering': ('-decision_date',),
            },
        ),
        migrations.AddIndex(
            model_name='courtordertjsp',
            index=models.Index(fields=['decision_date'], name='core_courto_decisio_69fb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='courtordertjsp',
            index=models.Index(fields=['number'], name='core_courto_number_5adf2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courtordertjsp',
            unique_together={('source', 'number')},
        ),
    ]
