# Generated by Django 2.1.5 on 2019-02-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_court_order_tjsp_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtordertjsp',
            name='subject',
            field=models.TextField(default=''),
        ),
    ]
