# Generated by Django 2.1.5 on 2019-02-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_subject_field_to_tjsp_court_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtordertjsp',
            name='petitioner_attorneys',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courtordertjsp',
            name='requested_attorneys',
            field=models.TextField(default=''),
        ),
    ]
