# Generated by Django 2.1.5 on 2019-02-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_attorneys_fields_to_tjsp_court_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtordertjsp',
            name='appeals',
            field=models.TextField(default=''),
        ),
    ]
